name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://vedantdubey19:$HF_TOKEN@huggingface.co/spaces/vedantdubey19/Nexchat main
